backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master

collections:
  - label: "Event"
    name: "event"
    folder: "src/events"
    create: true
    fields:
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }